
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./data:/app/data
    depends_on:
      - clamav
    networks:
      - app-network

  clamav:
    image: clamav/clamav-debian:1.2
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
    networks:
      - app-network

volumes:
  clamav_data:
    driver: local

networks:
  app-network:
    driver: bridge