
version: '3.8'

services:
  app:
    mem_limit: 4g
    cpus: 0.5
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TMPDIR: /var/tmp
    ports:
      - "5001:5000"
    volumes:
      - .:/workdir
      - shared_tmp:/var/tmp
    depends_on:
      - clamav
    networks:
      - app-network

  clamav:
    image: clamav/clamav-debian:1.2
    environment:
      TMPDIR: /var/tmp
      CLAMAV_UPDATE_ENABLED: "true"
    ports:
      - "3310:3310"
    volumes:
      - clamav_data:/var/lib/clamav
      - shared_tmp:/var/tmp
    networks:
      - app-network

  glances:
    image: nicolargo/glances:latest
    container_name: glances
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    network_mode: "host"
    environment:
      - GLANCES_OPT=-w -p 61209
      - GLANCES_OPT_ARG=--disable-plugin docker

volumes:
  clamav_data:
    driver: local
  shared_tmp:
    driver: local

networks:
  app-network:
    driver: bridge
